repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.3"
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.7.0"
    hooks:
      - id: pyproject-fmt
